#!/bin/sh
[ "${1:-}" = -q ] && shift
[ -z "${TEST_UCI_LOG:-}" ] || printf '%s\n' "$*" >>"$TEST_UCI_LOG"
case "${1:-}" in
	show)
		case "${2:-}" in
			routepolicy) printf 'routepolicy.main=main\n' ;;
			smartdns) printf 'smartdns.main=smartdns\n' ;;
			*) exit 1 ;;
		esac
		;;
	export)
		[ "${2:-}" = smartdns ] || exit 1
		printf "package smartdns\n\nconfig smartdns 'main'\n"
		;;
	import|batch) cat >/dev/null ;;
	commit|add_list|del_list|delete|set) exit 0 ;;
	get)
		case "${2:-}" in
			routepolicy.main.enabled) [ "${TEST_BAD_CONFIG:-0}" = 1 ] && echo broken || echo 1 ;;
			routepolicy.main.lan_interface) [ "${TEST_BAD_CONFIG:-0}" = 1 ] && echo 'lan"bad' || echo lan ;;
			routepolicy.main.default_interface) echo wan ;;
			routepolicy.main.policy_interface) echo usbwan ;;
			routepolicy.main.strict_enforcement) echo "${TEST_STRICT:-1}" ;;
			routepolicy.main.smartdns_enabled) echo "${TEST_SMARTDNS_ENABLED:-1}" ;;
			routepolicy.main.source_accounting) echo "${TEST_SOURCE_ACCOUNTING:-0}" ;;
			routepolicy.main.source_idle_timeout) echo "${TEST_SOURCE_IDLE_TIMEOUT:-600}" ;;
			routepolicy.main.source_max_entries) echo "${TEST_SOURCE_MAX_ENTRIES:-4096}" ;;
			routepolicy.main.dns_redirect|routepolicy.main.warm_restore|routepolicy.main.auto_update|routepolicy.main.update_via_policy_interface) echo 1 ;;
			routepolicy.main.route_table) [ "${TEST_BAD_CONFIG:-0}" = 1 ] && echo not-a-number || echo "${TEST_ROUTE_TABLE:-200}" ;;
			routepolicy.main.rule_priority) [ "${TEST_BAD_CONFIG:-0}" = 1 ] && echo -1 || echo "${TEST_RULE_PRIORITY:-12000}" ;;
			routepolicy.main.mark) [ "${TEST_BAD_CONFIG:-0}" = 1 ] && echo 0xzz || echo "${TEST_MARK:-0x100}" ;;
			routepolicy.main.mark_mask) [ "${TEST_BAD_CONFIG:-0}" = 1 ] && echo 0xzz || echo "${TEST_MARK_MASK:-0x100}" ;;
			routepolicy.main.smartdns_policy_group) echo policy ;;
			routepolicy.main.update_hour) echo 4 ;;
			routepolicy.main.update_minute) echo 17 ;;
			*) exit 1 ;;
		esac
		;;
esac
